export const actionTypes = {
  SET_CONTACTS: "SET_CONTACTS",
  ADD_CONTACT: "ADD_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  CLEAR_CONTACTS: "CLEAR_CONTACTS",
};
