export const actionTypes = {
  SET_CONTACTS: "SET_CONTACTS",
  ADD_CONTACT: "ADD_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  DELETE_CONTACTS: "DELETE_CONTACTS",
  FILTER_CONTACTS: "FILTER_CONTACTS",
  SORT_CONTACTS: "SORT_CONTACTS",
};
