export const actionTypes = {
  SET_TASKS: "SET_TASKS",
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK_CHECKBOX: "UPDATE_TASK_CHECKBOX",
  DELETE_ALL_TASKS: "DELETE_ALL_TASKS",
};
