export const actionTypes = {
  SET_CHART_AXIS: "SET_CHART_AXIS",
  SET_CHART_INFO: "SET_CHART_INFO",
  SET_OVERVIEW_INFO: "SET_OVERVIEW_INFO",
  SET_TASKS: "SET_TASKS",
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK_CHECKBOX: "UPDATE_TASK_CHECKBOX",
  DELETE_ALL_TASKS: "DELETE_ALL_TASKS",
  SET_TICKETS_DATA: "SET_TICKETS_DATA",
};
