export const actionTypes = {
  SET_CONTACTS: "SET_CONTACTS",
  ADD_CONTACT: "ADD_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  DELETE_CONTACTS: "DELETE_CONTACTS",
  SET_FILTER_TEXT: "SET_FILTER_TEXT",
  SET_EDIT_MODE: "SET_EDIT_MODE",
  SET_EDIT_CONTACT: "SET_EDIT_CONTACT",
  SHOW_CONTACTS_FORM: "SHOW_CONTACTS_FORM",
  SET_CURRENT_USER: "SET_CURRENT_USER",
};
